[phases.setup] 
cmds = ["apt-get update", "apt-get install -y libgl1 libglib2.0-0 libsm6 libxext6 libxrender-dev libgthread-2.0-0 libgtk2.0-0 libgtk-3-0 libjpeg-dev libpng-dev libtiff-dev"] 
 
[phases.install] 
cmds = ["pip install -r ml-service/reqs.txt"] 
 
[start] 
cmd = "cd ml-service && python app.py" 
